Use surf

diff --git a/_websrv b/_websrv
--- a/_websrv
+++ b/_websrv
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -vx
+set +vx
 # websrv - Start php server and browser
 # Started by lxsession's autostart, can be started manually.
 # Environmental variables IP & PORT can be set for php server, and URL for the
@@ -7,19 +7,19 @@ set -vx
 
 : ${IP:=%IP} # Set from INSTALL
 : ${PORT:=%PORT} # Set from INSTALL
-url=$IP:$PORT
-[[ $url = %IP:%PORT ]] && echo "Change %IP and %PORT in websrv before use!" &&
+site=$IP:$PORT
+[[ $site = %IP:%PORT ]] && echo "Change %IP and %PORT in websrv before use!" &&
 	exit 1
 : ${URL:=%URL} # Set from INSTALL
-: ${URL:=http://$url/index.html}
-cmd="/usr/bin/php -S $url -t $HOME/git/bulletin/web"
+: ${URL:=http://$site/index.html}
+cmd="/usr/bin/php -S $site -t $HOME/git/bulletin/web"
+brw='/usr/bin/surf'
 
 if [[ $1 = stop || $1 = kill ]]
 then
   pkill -f "$cmd" && echo "Web server terminated" ||
-	  echo "Web server was not running"
-	killall /usr/lib/chromium-browser/chromium-browser &&
-		echo "Browser terminated" ||
+		echo "Web server was not running"
+	killall "$brw" && echo "Browser terminated" ||
 		echo "Browser was not running"
   exit 0
 fi
@@ -32,13 +32,14 @@ pid=$!
 sleep 3
 if kill -0 $pid
 then
-	# Prevent post-crash dialogs
-	sed -i 's/"exited_cleanly": false/"exited_cleanly": true/' ~/.config/chromium/Default/Preferences
-	# Start browser in kiosk-mode, with no pinch allowed, allow file reads,
-	#  no update-available message ever, no error dialogs, and unencumbered.
-	DISPLAY=:0 chromium-browser $URL --kiosk --disable-pinch --allow-file-access-from-files --check-for-update-interval=31536000 --noerrdialogs --incognito &
-	echo "Web server and browser started on http://$url"
+	## Prevent post-crash dialogs
+	#sed -i 's/"exited_cleanly": false/"exited_cleanly": true/' ~/.config/chromium/Default/Preferences
+	## Start browser in kiosk-mode, with no pinch allowed, allow file reads,
+	##  no update-available message ever, no error dialogs, and unencumbered.
+	#DISPLAY=:0 chromium-browser $URL --kiosk --disable-pinch --allow-file-access-from-files --check-for-update-interval=31536000 --noerrdialogs --incognito &
+	DISPLAY=:0 "$brw" -bmpF "$URL"
+	echo "Web server and browser started on http://$site"
 	echo "Terminate by:  $0 stop"
 else
-	echo "ERROR: failed to start webserver on http://$url"
+	echo "ERROR: failed to start webserver on http://$site"
 fi
