Improve install

diff --git a/_websrv b/_websrv
--- a/_websrv
+++ b/_websrv
@@ -1,8 +1,10 @@
 #!/usr/bin/env bash
 # Started by lxsession's autostart
 
-url='http://bulletin:8888'
-cmd="/usr/bin/php -S $url -t /home/pi/git/bulletin/web"
+url="%IP:%PORT"
+[[ $url = %IP:%PORT ]] && echo "Change %IP and %PORT in websrv before use!" &&
+	exit 1
+cmd="/usr/bin/php -S $url -t $HOME/git/bulletin/web"
 
 if [[ $1 = stop || $1 = kill ]]
 then
@@ -14,5 +16,6 @@ fi
 pgrep -f "$cmd" && echo "Web server was running already " && exit 2
 
 [[ $1 = log ]] && null=$0.log || null=/dev/null
-$cmd 2>>"$null" &
-echo "Web server started on $url - terminate by: $0 stop"
+$cmd 2>"$null" &
+(($?)) && echo "Web server started on http://$url - terminate by: $0 stop" ||
+	echo "ERROR: failed to start webserver on http://$url"
